FROM python:3.11-slim
WORKDIR /app
COPY frontend/requirements.txt .
RUN pip install --default-timeout=300 --no-cache-dir -r requirements.txt
COPY frontend/ /app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]